# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.boot_timeout = 1000

  common_azure = Proc.new do |azure, override|
        config.vm.box = 'azure'
	config.ssh.pty= true
        azure.mgmt_certificate = 'cert/cert.pem'
        azure.mgmt_endpoint = 'https://management.core.windows.net'
        azure.subscription_id = '<YOUR SUBSCRIPTION ID>' # add here your subscription id
        azure.storage_acct_name = 'vagrantazure1'
        azure.vm_image = 'b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu_DAILY_BUILD-precise-12_04_5-LTS-amd64-server-20150709-en-us-30GB'
        azure.vm_user = 'ubuntu' # change to username on your local host
	azure.ssh_private_key_file = '/home/ubuntu/.ssh/id_rsa'	# change the path of id_rsa to yours
	azure.ssh_certificate_file = '/home/ubuntu/.ssh/ssh-cert.pem' # change the path of ssh-cer.pem to yours
        azure.vm_name = 'mpi-azure'
        azure.cloud_service_name = 'mpi-azure1' # same as vm_name. leave blank to auto-generate
        azure.deployment_name = 'mpi-azure1' # defaults to cloud_service_name
        azure.vm_location = 'East US' # e.g., West US
	azure.ssh_port = '22'
  end

  config.vm.define 'master' do |cfg|
    cfg.vm.provider :azure do |azure, override|
      common_azure.call azure, override
      azure.vm_name = 'master'
      azure.ssh_port = 2200
      azure.tcp_endpoints = '40000:40000'
    end
  end
  config.vm.define 'node-1' do |cfg|
    cfg.vm.provider :azure do |azure, override|
      common_azure.call azure, override
      azure.vm_name = 'node-1'
      azure.ssh_port = 2201
      azure.tcp_endpoints = '40000:40001'
    end
  end

  config.vm.define 'node-2' do |cfg|
    cfg.vm.provider :azure do |azure, override|
      common_azure.call azure, override
      azure.vm_name = 'node-2'
      azure.ssh_port = 2202
      azure.tcp_endpoints = '40000:40002'
    end
  end

  config.ssh.username = 'ubuntu' # modify this username
  config.ssh.private_key_path = "/home/ubuntu/.ssh/id_rsa" # modify this path 

end
