- name: create data directory
  file: path={{ mpi_dir }} state=directory

- name: mount nfs
  mount: name={{ mpi_dir }} src="master:{{ mpi_dir }}" fstype=nfs4 opts="proto=tcp,port=2049" state=mounted
