# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = "<YOUR ACCESS KEY>"
    aws.secret_access_key = "YOUR SECRET KEY"
    # More comprehensive region config
    aws.region_config "us-west-2" do |region|
      region.ami = "ami-87654321"
      region.keypair_name = "cpots-key"
    end
    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "/home/ubuntu/.ssh/id_rsa"
  end
end
